## Data Manipulation with Pandas
- efficient implementation of dataframes
- multidimensional arrays with row and column labels
- handles heterogeneous or missing data
- has data operations similar to databases or spreadsheets

In [1]:
import numpy as np
import pandas as pd
pd.__version__

'0.23.4'

### Panda Series
- one dimensional array of indexed data
- created from a list or an array
- similar to a python dictionary but maps typed keys to typed values

In [2]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [3]:
data.values  # a numpy array

array([0.25, 0.5 , 0.75, 1.  ])

In [4]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
# access data similar to numpy arrays
data[1]

0.5

In [6]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [7]:
# change the index to something else
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [8]:
# access data using index values
data['b']

0.5

In [9]:
# convert dictionary to series
population_dict = {'California': 38332521, 
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
dtype: int64

In [10]:
# supports slicing
population['California':'New York']

California    38332521
Texas         26448193
New York      19651127
dtype: int64

### Pandas Dataframe
- generalized array or specialized dictionary
- two dimensional array with flexible row and column indices / names

In [11]:
# think of dataframes as  a sequence of aligned
# series objects

area_dict = {'California': 413967,
             'Texas': 695662,
             'New York': 141297,
             'Florida': 170312}

area = pd.Series(area_dict)
area

California    413967
Texas         695662
New York      141297
Florida       170312
dtype: int64

In [12]:
# combine with population series

states = pd.DataFrame({'population': population,
                      'area': area})
states

population    area
California    38332521  413967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312

In [13]:
# row labels
states.index

Index(['California', 'Texas', 'New York', 'Florida'], dtype='object')

In [14]:
# column labels
states.columns

Index(['population', 'area'], dtype='object')

**Constructing dataframes**
- from a single series
- from any list of dictionaries
- from a two dimensional array
- from structured arrays

In [15]:
# create 2D array

x = np.random.rand(3, 2)
print(x)

[[0.91060228 0.11283198]
 [0.45661854 0.78112891]
 [0.93658628 0.27921332]]


In [16]:
pd.DataFrame(x, columns=['foo', 'bar'],
            index=['a', 'b', 'c'])

foo       bar
a  0.910602  0.112832
b  0.456619  0.781129
c  0.936586  0.279213

### Pandas Index Object

In [17]:
# index object as an immutable array
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [18]:
ind[1]

3

In [19]:
# ind[1] = 0  # cannot change any indices

In [20]:
# index as ordered sets
a = pd.Index([1, 3, 4, 7, 9])
b = pd.Index([2, 3, 5, 7, 11])

In [21]:
a & b  # intersection

Int64Index([3, 7], dtype='int64')

In [22]:
a | b  # union

Int64Index([1, 2, 3, 4, 5, 7, 9, 11], dtype='int64')

In [23]:
 a ^ b  # symmetric difference

Int64Index([1, 2, 4, 5, 9, 11], dtype='int64')

### Data Indexing and Selection

In [24]:
# some examples of data extraction
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [25]:
'a' in data

True

In [26]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [27]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [28]:
# add new value to data
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [29]:
# slice data by index
data['a':'c']  # final value included

a    0.25
b    0.50
c    0.75
dtype: float64

In [30]:
# slice by implicit integer index
data[0:2]  # like regular slicing, final value excluded

a    0.25
b    0.50
dtype: float64

In [31]:
# masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [32]:
# fancy indexing
i = ['a', 'e']
data[i]

a    0.25
e    1.25
dtype: float64

**Indexers**
- if your series has an explicit index, slicing will use the implicit index
- *loc* always uses explicit index
- *iloc* uses implicit index

In [33]:
# example to illustrate
data = pd.Series(['a', 'b', 'c'],
                 index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [34]:
data[1]  # explicit index

'a'

In [35]:
data[1:3]  # implicit for slicing

3    b
5    c
dtype: object

In [36]:
# use loc instead for explicit
print(data.loc[1])
print(data.loc[1:3])

a
1    a
3    b
dtype: object


In [37]:
# use iloc for implicit index
print(data.iloc[1])
print(data.iloc[1:3])

b
3    b
5    c
dtype: object


**Data Selection in DataFrame**

In [38]:
"""
rerun above code to create the dataframe 
containing population data for states
"""

data = pd.DataFrame({'area': area,
                     'population': population})
data

area  population
California  413967    38332521
Texas       695662    26448193
New York    141297    19651127
Florida     170312    19552860

In [39]:
# can access series like so:
data.area

California    413967
Texas         695662
New York      141297
Florida       170312
Name: area, dtype: int64

In [40]:
# add new series to dataframe
data['density'] = data['population'] / data['area']
data

area  population     density
California  413967    38332521   92.598011
Texas       695662    26448193   38.018740
New York    141297    19651127  139.076746
Florida     170312    19552860  114.806121

In [41]:
# view dataframe as an enhanced 2d array 
data.values

array([[4.13967000e+05, 3.83325210e+07, 9.25980114e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02]])

In [42]:
# transpose dataframe
data.T

California         Texas      New York       Florida
area        4.139670e+05  6.956620e+05  1.412970e+05  1.703120e+05
population  3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07
density     9.259801e+01  3.801874e+01  1.390767e+02  1.148061e+02

In [43]:
# single value grabs a row
data.values[0]

array([4.13967000e+05, 3.83325210e+07, 9.25980114e+01])

In [44]:
# grabs a column
data['area']

California    413967
Texas         695662
New York      141297
Florida       170312
Name: area, dtype: int64

In [45]:
# use iloc to index the dataframe similar to an array
data.iloc[:, :2]

area  population
California  413967    38332521
Texas       695662    26448193
New York    141297    19651127
Florida     170312    19552860

In [46]:
# explicit indexing
data.loc[:'New York', :'population']

area  population
California  413967    38332521
Texas       695662    26448193
New York    141297    19651127

In [47]:
# get the population where density > 100
data.loc[data.density > 100, ['population', 'density']]

population     density
New York    19651127  139.076746
Florida     19552860  114.806121

### Operating on Data

In [48]:
import pandas as pd
import numpy as np

In [49]:
# set seed and generate 4 random ints 
# between 0 and 10 as a series
rng = np.random.RandomState(42)
s = pd.Series(rng.randint(0, 10, 4))
s

0    6
1    3
2    7
3    4
dtype: int64

In [50]:
# generate a 3x4 dataframe of random ints
# between 0 and 10 
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                 columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [51]:
# applying a universal function preserves indices
np.exp(s)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [52]:
# same for dataframes
np.sin(df)

A         B         C         D
0 -0.279415  0.412118  0.909297 -0.279415
1  0.656987 -0.756802  0.141120  0.656987
2  0.656987  0.909297 -0.958924 -0.756802

In [53]:
# pandas will align indices in performing operations

area = pd.Series({'Alaska': 1723337,
                  'Texas': 695662,
                  'California': 423967},
                 name='area')

population = pd.Series({'California': 38332521,
                        'Texas': 26448193,
                        'New York': 19651127},
                       name='population')

In [54]:
population /  area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [55]:
population.divide(area, fill_value=0)

Alaska         0.000000
California    90.413926
New York            inf
Texas         38.018740
dtype: float64

**Index Alignment**

In [56]:
a = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                columns=list("AB"))
a

A   B
0  1  11
1  5   1

In [57]:
b = pd.DataFrame(rng.randint(0, 20, (3, 3)),
                columns=list("BAC"))
b

B   A   C
0   0  11  11
1  16   9  15
2  14  14  18

In [58]:
a + b  # indices are aligned and sorted

A     B   C
0  12.0  11.0 NaN
1  14.0  17.0 NaN
2   NaN   NaN NaN

In [59]:
# use fill_value to input the average of all values in A
fill = a.stack().mean()  # stack the rows first
fill

4.5

In [60]:
# add the mean of a to b where it's missing
a.add(b, fill_value=fill)

A     B     C
0  12.0  11.0  15.5
1  14.0  17.0  19.5
2  18.5  18.5  22.5

**Operations between DF and Series**

In [61]:
# a random 3x4 matrix of values between 0 and 10
a = rng.randint(10, size=(3, 4))
a

array([[6, 3, 8, 2],
       [4, 2, 6, 4],
       [8, 6, 1, 3]])

In [62]:
a - a[0]  # subtract all entries by the value of the first row

array([[ 0,  0,  0,  0],
       [-2, -1, -2,  2],
       [ 2,  3, -7,  1]])

In [67]:
# default operation is row wise for dataframes
df = pd.DataFrame(a, columns=list('QRST'))
df

Q  R  S  T
0  6  3  8  2
1  4  2  6  4
2  8  6  1  3

In [68]:
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -2 -1 -2  2
2  2  3 -7  1

In [69]:
# operate column wise - use axis command
df.subtract(df['R'], axis=0)

Q  R  S  T
0  3  0  5 -1
1  2  0  4  2
2  2  0 -5 -3

In [74]:
halfrow = df.iloc[0, ::2]  # every other element of the first row
halfrow

Q    6
S    8
Name: 0, dtype: int64

In [75]:
df - halfrow  
# Q column from df is subtracted by 6
# S column from df is subtracted by 8

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -2.0 NaN -2.0 NaN
2  2.0 NaN -7.0 NaN

### Handling Missing Data
- can use a mask to globally indicates missing values or
    - can be an entirely separate boolean array
- use a sentinel value that indicates a missing entry
    - some data-specific convention i.e. -9999 for missing int
- pandas uses sentinels for missing data
    - two existing python null values: NaN and None


***None* values**
- simple python object
- cannot be used in any arbitrary array
- only in arrays with data type = object (i.e. an array of python objects)

In [76]:
import numpy as np
import pandas as pd

In [77]:
vals1 = np.array([1, None, 3, 4])
vals1
# not an efficient array

array([1, None, 3, 4], dtype=object)

In [79]:
# since it's an object array, we cannot do aggregations
# vals1.sum()  # will produce an error

***NaN* values**
- special floating point value that all systems recognize

In [82]:
vals2 = np.array([1, np.nan, 3, 4])
vals2.dtype

dtype('float64')

In [84]:
# this array supports fast operations 
## but all operations with nan gives you nan
1 + np.nan

nan

In [85]:
vals2.sum()

nan

In [86]:
# use special aggregations that will ignore missing nan values
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2)

(8.0, 1.0, 4.0)

**None and NaN in Pandas**
- handles interchangeably with conversion where appropriate

In [87]:
a = pd.Series([1, np.nan, 2, None])
a

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [88]:
# use methods to indicate missing or null values
data = pd.Series([1, np.nan, 'hello', None])
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [89]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [90]:
data.notnull()

0     True
1    False
2     True
3    False
dtype: bool

In [91]:
data[data.notnull()]  # get only not null values

0        1
2    hello
dtype: object

In [92]:
data.dropna()  # get rid of null values

0        1
2    hello
dtype: object

In [93]:
# more options available in dataframe
df = pd.DataFrame([[1, np.nan, 2],
                   [2, 3, 5],
                   [np.nan, 4, 6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [94]:
# cannot drop single values
# can drop full rows or columns
df.dropna()  # default drops all row any any null value

0    1  2
1  2.0  3.0  5

In [95]:
df.dropna(axis='columns') 
# drops any column with nan
# can also do df.dropna(axis=1)

2
0  2
1  5
2  6

In [98]:
# but you lose a lot of data
# want to only drop rows with all nan or majority nan values
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [99]:
# use how or thresh
# default for how='any'
df.dropna(axis=1, how='all')  # drop if all values are null

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [106]:
# thresh lets you set some threshold
df.dropna(axis=0, thresh=3)  # sets the minimum number of non-nulls

0    1  2   3
1  2.0  3.0  5 NaN

**Fill null values**

In [107]:
data = pd.Series([1, np.nan, 2, None, 3],
                 index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [108]:
# fill null values using 0
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [109]:
# forward fill to propagate the previous values forward
data.fillna(method='ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [110]:
# or backfill
data.fillna(method='bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

### Hierarchical Indexing
- more than two dimensions, indexed by more than two keys
- use **MultiIndex** objects

In [1]:
import pandas as pd
import numpy as np

In [2]:
# bad way to represent 2d data in an 1d series:
# using python tuples as keys
index = [('California', 2000),
         ('California', 2010),
         ('New York', 2000),
         ('New York', 2010),
         ('Texas', 2000),
         ('Texas', 2010)]

populations = [33871648, 37253956,
               18976457, 19378102, 
               20851820, 25145561]

pop = pd.Series(populations, index=index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [3]:
# slice data like this:
pop[('California', 2010) : ('Texas', 2000)]

(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
dtype: int64

In [4]:
# how to get all 2010 data?
pop[[i for i in pop.index if i[1] == 2010]]

(California, 2010)    37253956
(New York, 2010)      19378102
(Texas, 2010)         25145561
dtype: int64

In [5]:
# use multiindex
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex(levels=[['California', 'New York', 'Texas'], [2000, 2010]],
           labels=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

In [6]:
# reindex the series:
pop = pop.reindex(index)
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [7]:
# get all 2010 data:
pop[:, 2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

In [11]:
# get all texas data
pop['Texas']

2000    20851820
2010    25145561
dtype: int64

In [12]:
# can also store the data as a dataframe
# this will create a column per year
pop_df = pop.unstack()
pop_df

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [13]:
# stack will turn wide data into long data:
pop_df.stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [14]:
# represent more dimensions in a Series
# for example, add population under 10
pop_df = pd.DataFrame({'total': pop,
                        'under18': [9267089, 9284094,
                                    4687374, 4328033, 
                                    5906301, 6879014]})
pop_df

total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4328033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [15]:
# new dataframe to show proportion of population under 18
f_u18 = pop_df['under18'] / pop_df['total']
f_u18

California  2000    0.273594
            2010    0.249211
New York    2000    0.247010
            2010    0.223347
Texas       2000    0.283251
            2010    0.273568
dtype: float64

In [16]:
f_u18.unstack()

2000      2010
California  0.273594  0.249211
New York    0.247010  0.223347
Texas       0.283251  0.273568